from .pdf_template_configuration import PDFTemplateConfigurationPDFGeneratorManager
from .pdf_template_configuration_variables import PDFTemplateConfigurationVariablesPDFGeneratorManager
from .pdf_generated import PDFGeneratedPDFGeneratorManager
from .text_page import TextPagePDFGeneratorManager
from .form import FormPDFGeneratorManager
from .field import FieldPDFGeneratorManager
from .form_value import FormValuePDFGeneratorManager