# Generated by Django 3.0.6 on 2020-05-29 15:10

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserExtended',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('timezone', models.IntegerField(default=-3)),
                ('is_admin', models.BooleanField(default=False)),
                ('temp_password', models.CharField(blank=True, default=None, max_length=250, null=True)),
            ],
            options={
                'db_table': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, default=None, max_length=400)),
                ('endpoint', models.CharField(db_index=True, default=None, max_length=280)),
                ('address', models.CharField(default=None, max_length=500, null=True)),
                ('zip_code', models.CharField(default=None, max_length=500, null=True)),
                ('street', models.CharField(default=None, max_length=500, null=True)),
                ('number', models.IntegerField(null=True)),
                ('neighborhood', models.CharField(default=None, max_length=500, null=True)),
                ('country', models.CharField(default=None, max_length=280, null=True)),
                ('state', models.CharField(default=None, max_length=280, null=True)),
                ('city', models.CharField(default=None, max_length=280, null=True)),
                ('cnpj', models.CharField(default=None, max_length=280, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_supercompany', models.BooleanField(default=False)),
                ('is_paying_company', models.BooleanField(default=False)),
                ('vindi_plan_id', models.CharField(db_index=True, default=None, max_length=280, null=True)),
                ('vindi_client_id', models.CharField(db_index=True, default=None, max_length=280, null=True)),
                ('vindi_product_id', models.CharField(db_index=True, default=None, max_length=280, null=True)),
                ('vindi_payment_profile_id', models.CharField(db_index=True, default=None, max_length=280, null=True)),
                ('vindi_signature_id', models.CharField(db_index=True, default=None, max_length=280, null=True)),
                ('partner', models.CharField(blank=True, default=None, max_length=500, null=True)),
            ],
            options={
                'db_table': 'company',
            },
        ),
        migrations.CreateModel(
            name='CompanyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('label_name', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'company_type',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='ProfileType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('label_name', models.CharField(blank=True, max_length=200, null=True)),
                ('can_edit', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'profiles',
            },
        ),
    ]
