# Generated by Django 3.0.6 on 2020-05-29 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        ('visualization', '0001_initial'),
        ('auth', '0011_update_proxy_permissions'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='charge_frequency_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='billing.ChargeFrequencyType'),
        ),
        migrations.AddField(
            model_name='company',
            name='company_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.CompanyType'),
        ),
        migrations.AddField(
            model_name='company',
            name='invoice_date_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='billing.InvoiceDateType'),
        ),
        migrations.AddField(
            model_name='company',
            name='payment_method_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='billing.PaymentMethodType'),
        ),
        migrations.AddField(
            model_name='company',
            name='shared_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.Company'),
        ),
        migrations.AddField(
            model_name='userextended',
            name='company',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='authentication.Company'),
        ),
        migrations.AddField(
            model_name='userextended',
            name='data_type',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='visualization.VisualizationType'),
        ),
        migrations.AddField(
            model_name='userextended',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='userextended',
            name='profile',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='authentication.ProfileType'),
        ),
        migrations.AddField(
            model_name='userextended',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
