# Generated by Django 3.0.6 on 2020-07-19 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20200608_1957'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companytype',
            options={'ordering': ('order',)},
        ),
        migrations.AlterModelOptions(
            name='profiletype',
            options={'ordering': ('order',)},
        ),
        migrations.AlterModelOptions(
            name='visualizationtype',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='companytype',
            name='order',
            field=models.BigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='profiletype',
            name='order',
            field=models.BigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='visualizationtype',
            name='order',
            field=models.BigIntegerField(default=1),
        ),
    ]
