# Generated by Django 3.0.6 on 2020-07-21 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20200719_1720'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(max_length=50)),
                ('country_name', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=400)),
                ('state_code', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=400)),
                ('order', models.BigIntegerField(default=1)),
            ],
            options={
                'db_table': 'address_type',
                'ordering': ('order',),
            },
        ),
    ]
