# Generated by Django 3.0.6 on 2020-07-22 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_addresstype'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AddressType',
            new_name='AddressHelper',
        ),
        migrations.AlterModelTable(
            name='addresshelper',
            table='address_helper',
        ),
    ]
