# Generated by Django 3.0.6 on 2020-07-24 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_auto_20200722_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='additional_details',
            field=models.CharField(default=None, max_length=280, null=True),
        ),
    ]
