# Generated by Django 3.1 on 2020-08-18 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_company_additional_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextended',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
