# Generated by Django 3.1 on 2020-08-28 19:28

from django.db import migrations
import django.db.models.manager
import reflow_server.authentication.managers.user_extended
import reflow_server.billing.managers.user_extended
import reflow_server.data.managers.user_extended
import reflow_server.formulary.managers.user_extended
import reflow_server.notification.managers.user_extended
import reflow_server.theme.managers.user_extended


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_auto_20200818_0005'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userextended',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('authentication_', reflow_server.authentication.managers.user_extended.UserExtendedAuthenticationManager()),
                ('billing_', reflow_server.billing.managers.user_extended.UserExtendedBillingManager()),
                ('data_', reflow_server.data.managers.user_extended.UserExtendedDataManager()),
                ('formulary_', reflow_server.formulary.managers.user_extended.UserExtendedFormularyManager()),
                ('notification_', reflow_server.notification.managers.user_extended.UserExtendedNotificationManager()),
                ('theme_', reflow_server.theme.managers.user_extended.UserExtendedThemeManager()),
            ],
        ),
    ]
