# Generated by Django 3.1 on 2020-08-28 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_auto_20200828_1928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='additional_details',
        ),
        migrations.RemoveField(
            model_name='company',
            name='address',
        ),
        migrations.RemoveField(
            model_name='company',
            name='charge_frequency_type',
        ),
        migrations.RemoveField(
            model_name='company',
            name='city',
        ),
        migrations.RemoveField(
            model_name='company',
            name='cnpj',
        ),
        migrations.RemoveField(
            model_name='company',
            name='country',
        ),
        migrations.RemoveField(
            model_name='company',
            name='invoice_date_type',
        ),
        migrations.RemoveField(
            model_name='company',
            name='is_paying_company',
        ),
        migrations.RemoveField(
            model_name='company',
            name='is_supercompany',
        ),
        migrations.RemoveField(
            model_name='company',
            name='neighborhood',
        ),
        migrations.RemoveField(
            model_name='company',
            name='number',
        ),
        migrations.RemoveField(
            model_name='company',
            name='payment_method_type',
        ),
        migrations.RemoveField(
            model_name='company',
            name='state',
        ),
        migrations.RemoveField(
            model_name='company',
            name='street',
        ),
        migrations.RemoveField(
            model_name='company',
            name='vindi_client_id',
        ),
        migrations.RemoveField(
            model_name='company',
            name='vindi_payment_profile_id',
        ),
        migrations.RemoveField(
            model_name='company',
            name='vindi_plan_id',
        ),
        migrations.RemoveField(
            model_name='company',
            name='vindi_product_id',
        ),
        migrations.RemoveField(
            model_name='company',
            name='vindi_signature_id',
        ),
        migrations.RemoveField(
            model_name='company',
            name='zip_code',
        ),
    ]
