# Generated by Django 3.1 on 2020-09-02 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_auto_20200828_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo_image_bucket',
            field=models.CharField(default='reflow-crm', max_length=200),
        ),
        migrations.AddField(
            model_name='company',
            name='logo_image_path',
            field=models.CharField(default='company-logo', max_length=250),
        ),
        migrations.AddField(
            model_name='company',
            name='logo_image_url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
