# Generated by Django 3.2.5 on 2021-09-21 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_publicaccess'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextended',
            name='timezone_name',
            field=models.CharField(default='America/Sao_Paulo', max_length=400),
        ),
    ]
