# Generated by Django 3.2.5 on 2021-11-09 07:23

from django.db import migrations


def migrate_api_access_token(apps, schema_editor):
    from uuid import uuid4
    UserExtended = apps.get_model('authentication', 'UserExtended')
    APIAccessToken = apps.get_model('authentication', 'APIAccessToken')

    for user in UserExtended.objects.filter(profile__name='admin'):
        APIAccessToken.objects.update_or_create(
            user=user, 
            company=user.company, 
            defaults={
                'access_token': str(uuid4())
            }
        )

class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_alter_apiaccesstoken_access_token'),
    ]

    operations = [
        migrations.RunPython(migrate_api_access_token)
    ]
