# Generated by Django 3.2.5 on 2022-02-02 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_auto_20211109_0723'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextended',
            name='profile_image_bucket',
            field=models.CharField(default='reflow-crm', max_length=200),
        ),
        migrations.AddField(
            model_name='userextended',
            name='profile_image_path',
            field=models.CharField(default='company-logo', max_length=250),
        ),
        migrations.AddField(
            model_name='userextended',
            name='profile_image_url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
