# Generated by Django 3.2.5 on 2022-02-03 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0016_auto_20220202_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextended',
            name='profile_image_path',
            field=models.CharField(default='user-profile', max_length=250),
        ),
    ]
