# Generated by Django 3.1.4 on 2021-05-27 18:29
from django.db import migrations, transaction
from django.db.models import Q

import uuid


@transaction.atomic
def migrate_formula_to_formula_fields(apps, schema_editor):
    Field = apps.get_model('formulary', 'Field')
    FieldType = apps.get_model('formulary', 'FieldType')
    
    formula_field_type = FieldType.objects.filter(type='formula').first()
    fields = Field.objects.exclude(Q(formula_configuration='') | Q(formula_configuration__isnull=True))
    for formula_field_instance in fields:
        formula_field_instance.type = formula_field_type
        formula_field_instance.save()
    
class Migration(migrations.Migration):
    dependencies = [
        ('formula', '0003_auto_20210526_1335'),
    ]

    operations = [
        migrations.RunPython(migrate_formula_to_formula_fields)
    ]
