# Generated by Django 3.2.5 on 2021-08-09 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formula', '0004_auto_20210527_1829'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormulaBuiltinLibraryModuleAttributeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_name', models.CharField(max_length=240)),
                ('related_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='formula_builtin_library_module_attribute_type_related_to', to='formula.formulabuiltinlibrarymoduleattributetype')),
            ],
            options={
                'db_table': 'formula_builtin_library_module_attribute_type',
            },
        ),
        migrations.CreateModel(
            name='FormulaBuiltinLibraryModuleType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.TextField()),
            ],
            options={
                'db_table': 'formula_builtin_library_module_type',
            },
        ),
        migrations.CreateModel(
            name='FormulaContextBuiltinLibraryType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation', models.TextField()),
                ('attribute_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formula_context_builtin_library_type_library_attributes', to='formula.formulabuiltinlibrarymoduleattributetype')),
                ('module_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formula_context_builtin_library_type_library_module', to='formula.formulabuiltinlibrarymoduletype')),
                ('related_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='formula_context_builtin_library_type_related_to', to='formula.formulacontextbuiltinlibrarytype')),
            ],
            options={
                'db_table': 'formula_context_builtin_library_type',
            },
        ),
    ]
