# Generated by Django 3.2.5 on 2021-08-09 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formula', '0005_formulabuiltinlibrarymoduleattributetype_formulabuiltinlibrarymoduletype_formulacontextbuiltinlibrar'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulacontextbuiltinlibrarytype',
            name='context_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='formula_context_builtin_library_type_library_contexts', to='formula.formulacontexttype'),
        ),
        migrations.AddField(
            model_name='formulacontextbuiltinlibrarytype',
            name='original_value',
            field=models.TextField(default='teste'),
            preserve_default=False,
        ),
    ]
