# Generated by Django 3.2.5 on 2021-08-13 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formula', '0006_auto_20210809_0553'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormulaObjectType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'formula_object_type',
            },
        ),
        migrations.AddField(
            model_name='formulacontextbuiltinlibrarytype',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='formulacontextbuiltinlibrarytype',
            name='is_required_attribute',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='formulacontextbuiltinlibrarytype',
            name='parameter_object_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='formula_context_builtin_library_type_related_to', to='formula.formulaobjecttype'),
        ),
    ]
