# Generated by Django 3.2.5 on 2021-08-13 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formula', '0007_auto_20210813_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formulacontextbuiltinlibrarytype',
            name='parameter_object_type',
        ),
        migrations.DeleteModel(
            name='FormulaObjectType',
        ),
    ]
