# Generated by Django 3.2.5 on 2021-08-13 22:17

from django.db import migrations

def migrate_company_to_formula_context(apps, schema_editor):
    Company = apps.get_model('authentication', 'Company')
    FormulaContextForCompany = apps.get_model('formula', 'FormulaContextForCompany')
    FormulaContextType = apps.get_model('formula', 'FormulaContextType')

    formula_context_type = FormulaContextType.objects.filter(name='portuguese').first()
    
    for company in Company.objects.all():
        FormulaContextForCompany.objects.update_or_create(
            company=company,
            context_type=formula_context_type
        )
    
class Migration(migrations.Migration):

    dependencies = [
        ('formula', '0008_auto_20210813_1641'),
    ]

    operations = [
        migrations.RunPython(migrate_company_to_formula_context)
    ]
