# Generated by Django 3.2.5 on 2021-08-19 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formula', '0009_auto_20210813_2217'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FormulaContextBuiltinLibraryType',
            new_name='FormulaContextBuiltinLibrary',
        ),
    ]
