# Generated by Django 3.2.5 on 2021-10-21 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formula', '0010_rename_formulacontextbuiltinlibrarytype_formulacontextbuiltinlibrary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulacontextattributetype',
            name='attribute_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formula_attribute_type_attributes', to='formula.formulaattributetype'),
        ),
    ]
