version: '3.3'
services:
  redis: 
    image: redis
    ports:
      - "6379:6379"
  db:
    image: postgres
    volumes:
      - ./init.sh:/docker-entrypoint-initdb.d/init.sh
    ports:
      - "5432:5432"
  localstack:
    image: localstack/localstack
    ports:
      - "4567-4584:4567-4584"
      - "4585:4585"
    environment:
      - SERVICES=s3
      - DEBUG=${DEBUG- }
      - DATA_DIR=${DATA_DIR- }
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
  reflow_server:
    build: .
    command: pypy3 manage.py run
    environment:
      - CONFIG=development
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
      - localstack