# Generated by Django 3.0.6 on 2020-06-08 19:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data', '0001_initial'),
        ('formulary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notification', models.CharField(max_length=500)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.DynamicForm')),
            ],
            options={
                'db_table': 'notification',
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='NotificationConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('for_company', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=500)),
                ('text', models.CharField(max_length=500)),
                ('days_diff', models.CharField(db_index=True, max_length=100)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formulary.Field')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formulary.Form')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notification_configuration',
            },
        ),
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_new', models.BooleanField(default=True)),
                ('has_read', models.BooleanField(default=False)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notification.Notification')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_notification',
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='PreNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.DateTimeField()),
                ('has_sent', models.BooleanField(default=False)),
                ('is_sending', models.BooleanField(default=False)),
                ('dynamic_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.DynamicForm')),
                ('notification_configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notification.NotificationConfiguration')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pre_notification',
            },
        ),
        migrations.CreateModel(
            name='NotificationConfigurationVariable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=1)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formulary.Field')),
                ('notification_configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_configuration_variables', to='notification.NotificationConfiguration')),
            ],
            options={
                'db_table': 'notification_configuration_variable',
                'ordering': ('order',),
            },
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_configuration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='notification.NotificationConfiguration'),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
