# Generated by Django 3.0.6 on 2020-07-19 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationconfigurationvariable',
            name='order',
            field=models.BigIntegerField(default=1),
        ),
    ]
