# Generated by Django 3.2.5 on 2021-09-09 22:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('integration', '0001_initial'),
        ('authentication', '0011_publicaccess'),
    ]

    operations = [
        migrations.CreateModel(
            name='Automation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.company')),
            ],
            options={
                'db_table': 'automation',
            },
        ),
        migrations.CreateModel(
            name='AutomationApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('website', models.CharField(max_length=500)),
                ('logo_url', models.CharField(max_length=500)),
                ('integration_authentication', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='integration.integrationauthentication')),
            ],
            options={
                'db_table': 'automation_app',
            },
        ),
        migrations.CreateModel(
            name='AutomationAppTrigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('description', models.TextField()),
                ('script', models.TextField()),
                ('trigger_webhook', models.CharField(max_length=500)),
                ('automation_app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automation.automationapp')),
            ],
            options={
                'db_table': 'automation_app_trigger',
            },
        ),
        migrations.CreateModel(
            name='AutomationInputDataFormulary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'automation_input_data_formulary',
            },
        ),
        migrations.CreateModel(
            name='AutomationInputFieldType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=280)),
                ('order', models.BigIntegerField()),
            ],
            options={
                'db_table': 'automation_input_field_type',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='AutomationInputFormulary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=280)),
            ],
            options={
                'db_table': 'automation_input_formulary',
            },
        ),
        migrations.CreateModel(
            name='TriggerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=280)),
                ('order', models.BigIntegerField()),
            ],
            options={
                'db_table': 'trigger_type',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='AutomationTrigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_trigger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automation.automationapptrigger')),
                ('automation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='automation.automation')),
                ('input_data', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='automation.automationinputdataformulary')),
            ],
            options={
                'db_table': 'automation_trigger',
            },
        ),
        migrations.CreateModel(
            name='AutomationPooling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pool_id', models.UUIDField(blank=True, default=uuid.uuid4, null=True)),
                ('next_pool', models.DateTimeField(auto_now_add=True)),
                ('pool_data', models.TextField()),
                ('has_evaluated', models.BooleanField(default=False)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.company')),
            ],
            options={
                'db_table': 'automation_pooling',
            },
        ),
        migrations.CreateModel(
            name='AutomationInputSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=280)),
                ('show_section_name', models.BooleanField(default=True)),
                ('formulary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automation.automationinputformulary')),
            ],
            options={
                'db_table': 'automation_input_section',
            },
        ),
        migrations.CreateModel(
            name='AutomationInputField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('is_required', models.BooleanField(default=False)),
                ('field_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automation.automationinputfieldtype')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automation.automationinputsection')),
            ],
            options={
                'db_table': 'automation_input_field',
            },
        ),
        migrations.CreateModel(
            name='AutomationInputDataSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('formulary_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automation.automationinputdataformulary')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automation.automationinputsection')),
            ],
            options={
                'db_table': 'automation_input_data_section',
            },
        ),
        migrations.AddField(
            model_name='automationinputdataformulary',
            name='formulary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automation.automationinputformulary'),
        ),
        migrations.CreateModel(
            name='AutomationInputDataFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('value', models.TextField()),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automation.automationinputfield')),
                ('formulary_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automation.automationinputdataformulary')),
                ('section_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automation.automationinputdatasection')),
            ],
            options={
                'db_table': 'automation_input_data_field_value',
            },
        ),
        migrations.AddField(
            model_name='automationapptrigger',
            name='input_formulary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automation.automationinputformulary'),
        ),
        migrations.AddField(
            model_name='automationapptrigger',
            name='trigger_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automation.triggertype'),
        ),
        migrations.CreateModel(
            name='AutomationAppAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('description', models.TextField()),
                ('script', models.TextField()),
                ('automation_app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automation.automationapp')),
                ('input_formulary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automation.automationinputformulary')),
            ],
            options={
                'db_table': 'automation_app_action',
            },
        ),
        migrations.CreateModel(
            name='AutomationAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automation.automationappaction')),
                ('automation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automation.automation')),
                ('input_data', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='automation.automationinputdataformulary')),
            ],
            options={
                'db_table': 'automation_action',
            },
        ),
    ]
