# Generated by Django 3.2.5 on 2021-09-15 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formula', '0010_rename_formulacontextbuiltinlibrarytype_formulacontextbuiltinlibrary'),
        ('automation', '0003_auto_20210914_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationapp',
            name='flow_context',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='formula.formulacontexttype'),
        ),
    ]
