# Generated by Django 3.2.5 on 2021-09-21 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0004_automationapp_flow_context'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationaction',
            name='custom_script',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='automationappaction',
            name='embbed_formulary_url',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='automationapptrigger',
            name='embbed_formulary_url',
            field=models.TextField(null=True),
        ),
    ]
