# Generated by Django 3.2.5 on 2021-09-21 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0005_auto_20210921_0334'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationDebugTriggerData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_as_string', models.TextField()),
            ],
            options={
                'db_table': 'automation_debug_trigger_data',
            },
        ),
        migrations.AddField(
            model_name='automationtrigger',
            name='debug_data',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='automation.automationdebugtriggerdata'),
        ),
    ]
