# Generated by Django 3.2.5 on 2021-09-21 21:19

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0006_auto_20210921_1449'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationInputSectionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=280)),
                ('order', models.BigIntegerField()),
            ],
            options={
                'db_table': 'automation_input_section_type',
                'ordering': ('order',),
            },
        ),
        migrations.AlterModelManagers(
            name='automationdebugtriggerdata',
            managers=[
                ('automation_', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='automationappaction',
            name='enable_custom_script',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='automationdebugtriggerdata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='automationdebugtriggerdata',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='automationinputsection',
            name='section_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='automation.automationinputsectiontype'),
            preserve_default=False,
        ),
    ]
