# Generated by Django 3.2.5 on 2021-09-22 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0007_auto_20210921_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automationaction',
            name='automation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_actions', to='automation.automation'),
        ),
        migrations.AlterField(
            model_name='automationappaction',
            name='automation_app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_app_actions', to='automation.automationapp'),
        ),
        migrations.AlterField(
            model_name='automationapptrigger',
            name='automation_app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_app_triggers', to='automation.automationapp'),
        ),
        migrations.AlterField(
            model_name='automationtrigger',
            name='automation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='automation_trigger', to='automation.automation'),
        ),
        migrations.CreateModel(
            name='AutomationTriggerLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('result', models.TextField()),
                ('trigger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automation.automationtrigger')),
            ],
            options={
                'db_table': 'automation_trigger_log',
            },
        ),
        migrations.CreateModel(
            name='AutomationActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('result', models.TextField()),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automation.automationaction')),
            ],
            options={
                'db_table': 'automation_action_log',
            },
        ),
    ]
