# Generated by Django 3.2.5 on 2021-09-27 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0008_auto_20210922_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationapp',
            name='app_color',
            field=models.CharField(default='#0dbf7e', max_length=400),
        ),
        migrations.AddField(
            model_name='automationapp',
            name='is_internal_app',
            field=models.BooleanField(default=False),
        ),
    ]
