# Generated by Django 3.2.5 on 2021-09-28 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0009_auto_20210927_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automationinputfield',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_fields', to='automation.automationinputsection'),
        ),
        migrations.AlterField(
            model_name='automationinputsection',
            name='formulary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formulary_sections', to='automation.automationinputformulary'),
        ),
    ]
