# Generated by Django 3.2.5 on 2021-09-29 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0010_auto_20210928_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationinputfield',
            name='script_to_load_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AutomationInputFieldOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(db_index=True, max_length=500)),
                ('order', models.BigIntegerField()),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_field_options', to='automation.automationinputfield')),
            ],
            options={
                'db_table': 'automation_input_field_option',
            },
        ),
        migrations.CreateModel(
            name='AutomationInputFieldConditionsToReload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automation.automationinputfield')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_conditions_to_reload', to='automation.automationinputfield')),
            ],
            options={
                'db_table': 'automation_input_field_conditions_to_reload',
            },
        ),
    ]
