# Generated by Django 3.2.5 on 2021-10-01 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0011_auto_20210929_2130'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='automationinputfieldoption',
            options={'ordering': ('order',)},
        ),
        migrations.AlterField(
            model_name='automationinputdatafieldvalue',
            name='section_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_record_fields', to='automation.automationinputdatasection'),
        ),
        migrations.AlterField(
            model_name='automationinputdatasection',
            name='formulary_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formulary_record_sections', to='automation.automationinputdataformulary'),
        ),
    ]
