branch-defaults:
  master:
    environment: null
    group_suffix: null
environment-defaults:
  reflow-crm-django-web:
    branch: null
    repository: null
global:
  application_name: reflow-crm
  branch: null
  default_ec2_keyname: reflow
  default_platform: Docker 18.06.1-ce
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
workspace_type: Application
