# Generated by Django 3.2.5 on 2022-01-10 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0002_auto_20211202_0328'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IntegrationAuthenticationType',
            new_name='IntegrationServiceType',
        ),
        migrations.AlterModelTable(
            name='integrationservicetype',
            table='integration_service_type',
        ),
    ]
