# Generated by Django 3.1 on 2020-12-01 01:08

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_generator', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='pdftemplateconfiguration',
            managers=[
                ('pdf_generator_', django.db.models.manager.Manager()),
            ],
        ),
    ]
