# Generated by Django 3.1 on 2020-12-03 23:08

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_generator', '0002_auto_20201201_0108'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='pdftemplateconfigurationrichtext',
            managers=[
                ('pdf_generator_', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='pdftemplateconfigurationvariables',
            managers=[
                ('pdf_generator_', django.db.models.manager.Manager()),
            ],
        ),
    ]
