# Generated by Django 3.1 on 2020-12-11 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rich_text', '0009_textcontent_text_size'),
        ('pdf_generator', '0003_auto_20201203_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdftemplateconfiguration',
            name='rich_text',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rich_text.textpage'),
        ),
    ]
