# Generated by Django 3.1 on 2020-12-11 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_generator', '0004_pdftemplateconfiguration_rich_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pdftemplateconfiguration',
            old_name='rich_text',
            new_name='rich_text_page',
        ),
        migrations.DeleteModel(
            name='PDFTemplateConfigurationRichText',
        ),
    ]
