# Generated by Django 3.1.4 on 2020-12-12 03:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_auto_20200902_1555'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pdf_generator', '0005_auto_20201211_1634'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFGenerated',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.company')),
                ('pdf_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdf_generator.pdftemplateconfiguration')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pdf_generated',
            },
            managers=[
                ('pdf_generator_', django.db.models.manager.Manager()),
            ],
        ),
    ]
