# Generated by Django 3.1.4 on 2021-02-10 23:09

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_generator', '0007_pdftemplateallowedtextblock'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pdftemplateconfiguration',
            options={'ordering': ('-updated_at',)},
        ),
        migrations.AlterModelManagers(
            name='pdftemplateallowedtextblock',
            managers=[
                ('pdf_generator_', django.db.models.manager.Manager()),
            ],
        ),
    ]
