# Generated by Django 3.2.5 on 2021-08-19 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_generator', '0008_auto_20210210_2309'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='pdftemplateconfiguration',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='pdftemplateconfigurationvariables',
            managers=[
            ],
        ),
    ]
