# Generated by Django 3.0.6 on 2020-06-29 16:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractfiledata',
            name='file_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
