# Generated by Django 3.1 on 2020-09-17 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0002_extractfiledata_file_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ListingTotalForField',
        ),
    ]
