# Generated by Django 3.1.4 on 2021-05-20 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0003_delete_listingtotalforfield'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExtractFileData',
        ),
    ]
