# Generated by Django 3.0.6 on 2020-06-14 02:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('formulary', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('is_public', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'theme',
            },
        ),
        migrations.CreateModel(
            name='ThemeField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_configuration_mask', models.CharField(blank=True, max_length=250, null=True)),
                ('formula_configuration', models.CharField(blank=True, max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=300)),
                ('label_name', models.CharField(blank=True, max_length=300, null=True)),
                ('placeholder', models.CharField(blank=True, max_length=450, null=True)),
                ('required', models.BooleanField(default=True)),
                ('order', models.BigIntegerField()),
                ('is_unique', models.BooleanField(default=False)),
                ('field_is_hidden', models.BooleanField(default=False)),
                ('label_is_hidden', models.BooleanField(default=False)),
                ('date_configuration_auto_create', models.BooleanField(default=False)),
                ('date_configuration_auto_update', models.BooleanField(default=False)),
                ('number_configuration_allow_negative', models.BooleanField(default=True)),
                ('number_configuration_allow_zero', models.BooleanField(default=True)),
                ('date_configuration_date_format_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='formulary.FieldDateFormatType')),
            ],
            options={
                'db_table': 'theme_field',
            },
        ),
        migrations.CreateModel(
            name='ThemeForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('form_name', models.CharField(db_index=True, max_length=150)),
                ('label_name', models.CharField(max_length=150)),
                ('order', models.BigIntegerField()),
                ('conditional_value', models.CharField(blank=True, max_length=200, null=True)),
                ('form_id', models.BigIntegerField(blank=True, default=None, null=True)),
                ('conditional_on_field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conditional_on_theme_field', to='theme.ThemeField')),
                ('conditional_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='formulary.ConditionalType')),
                ('depends_on', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='depends_on_theme_form', to='theme.ThemeForm')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theme_form', to='theme.Theme')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formulary.SectionType')),
            ],
            options={
                'db_table': 'theme_form',
            },
        ),
        migrations.CreateModel(
            name='ThemeKanbanCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default', models.BooleanField(default=False)),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theme.Theme')),
            ],
            options={
                'db_table': 'theme_kanban_card',
            },
        ),
        migrations.CreateModel(
            name='ThemeNotificationConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('for_company', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=500)),
                ('text', models.CharField(max_length=500)),
                ('days_diff', models.CharField(db_index=True, max_length=100)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theme.ThemeField')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theme.ThemeForm')),
            ],
            options={
                'db_table': 'theme_notification_configuration',
            },
        ),
        migrations.CreateModel(
            name='ThemeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('label_name', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'group_type',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='ThemePhotos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=300)),
                ('url', models.CharField(max_length=1000)),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theme_photos', to='theme.Theme')),
            ],
            options={
                'db_table': 'theme_photos',
            },
        ),
        migrations.CreateModel(
            name='ThemeNotificationConfigurationVariable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=1)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theme.ThemeField')),
                ('notification_configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theme.ThemeNotificationConfiguration')),
            ],
            options={
                'db_table': 'theme_notification_configuration_variable',
            },
        ),
        migrations.CreateModel(
            name='ThemeListingTotalForField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theme.ThemeField')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theme.Theme')),
            ],
            options={
                'db_table': 'theme_listing_total_for_fields',
            },
        ),
        migrations.CreateModel(
            name='ThemeKanbanDimensionOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('options', models.CharField(max_length=500)),
                ('order', models.BigIntegerField()),
                ('default', models.BooleanField(default=False)),
                ('dimension', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='theme.ThemeField')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theme.Theme')),
            ],
            options={
                'db_table': 'theme_kanban_dimension_order',
            },
        ),
        migrations.CreateModel(
            name='ThemeKanbanCardField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='theme.ThemeField')),
                ('kanban_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='theme_kanban_card_fields', to='theme.ThemeKanbanCard')),
            ],
            options={
                'db_table': 'theme_kanban_card_field',
            },
        ),
        migrations.CreateModel(
            name='ThemeFieldOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('option', models.CharField(db_index=True, max_length=500)),
                ('order', models.BigIntegerField()),
                ('field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='theme_field_option', to='theme.ThemeField')),
            ],
            options={
                'db_table': 'theme_field_options',
            },
        ),
        migrations.AddField(
            model_name='themefield',
            name='form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='theme_form_fields', to='theme.ThemeForm'),
        ),
        migrations.AddField(
            model_name='themefield',
            name='form_field_as_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='theme.ThemeField'),
        ),
        migrations.AddField(
            model_name='themefield',
            name='number_configuration_number_format_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='formulary.FieldNumberFormatType'),
        ),
        migrations.AddField(
            model_name='themefield',
            name='period_configuration_period_interval_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='formulary.FieldPeriodIntervalType'),
        ),
        migrations.AddField(
            model_name='themefield',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formulary.FieldType'),
        ),
        migrations.AddField(
            model_name='theme',
            name='company_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='theme_company_type', to='theme.ThemeType'),
        ),
        migrations.AddField(
            model_name='theme',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='theme_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
