# Generated by Django 3.1 on 2020-09-17 21:02

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('formulary', '0002_auto_20200719_1720'),
        ('dashboard', '0003_auto_20200917_2102'),
        ('theme', '0002_auto_20200719_1720'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThemeDashboardChartConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=350)),
                ('for_company', models.BooleanField(default=False)),
                ('aggregation_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.aggregationtype')),
                ('chart_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.charttype')),
            ],
            options={
                'db_table': 'theme_dashboard_chart_configuration',
            },
        ),
        migrations.AlterModelOptions(
            name='themeform',
            options={'ordering': ('order',)},
        ),
        migrations.AlterModelOptions(
            name='themekanbandimensionorder',
            options={'ordering': ('order',)},
        ),
        migrations.AlterModelManagers(
            name='theme',
            managers=[
                ('theme_', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='themefield',
            managers=[
                ('theme_', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='themefieldoptions',
            managers=[
                ('theme_', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='themeform',
            managers=[
                ('theme_', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='themekanbancard',
            managers=[
                ('theme_', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='themekanbancardfield',
            managers=[
                ('theme_', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='themekanbandimensionorder',
            managers=[
                ('theme_', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='themenotificationconfiguration',
            managers=[
                ('theme_', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='themenotificationconfigurationvariable',
            managers=[
                ('theme_', django.db.models.manager.Manager()),
            ],
        ),
        migrations.DeleteModel(
            name='ThemeListingTotalForField',
        ),
        migrations.AddField(
            model_name='themedashboardchartconfiguration',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theme.themeform'),
        ),
        migrations.AddField(
            model_name='themedashboardchartconfiguration',
            name='label_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theme_dashboard_chart_configuration_label_fields', to='theme.themefield'),
        ),
        migrations.AddField(
            model_name='themedashboardchartconfiguration',
            name='number_format_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formulary.fieldnumberformattype'),
        ),
        migrations.AddField(
            model_name='themedashboardchartconfiguration',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theme.theme'),
        ),
        migrations.AddField(
            model_name='themedashboardchartconfiguration',
            name='value_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theme_dashboard_chart_configuration_value_fields', to='theme.themefield'),
        ),
    ]
