# Generated by Django 3.1 on 2020-09-17 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0003_auto_20200917_2102'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='themefield',
            options={'ordering': ('order',)},
        ),
        migrations.AlterModelOptions(
            name='themenotificationconfigurationvariable',
            options={'ordering': ('order',)},
        ),
    ]
