# Generated by Django 3.1 on 2020-09-29 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_auto_20200902_1555'),
        ('theme', '0004_auto_20200917_2105'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='theme',
            managers=[
            ],
        ),
        migrations.RenameField(
            model_name='theme',
            old_name='company_type',
            new_name='theme_type'
        ),
        migrations.AddField(
            model_name='theme',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='theme_company', to='authentication.company'),
        ),
        migrations.AlterModelTable(
            name='themetype',
            table='theme_type',
        ),
    ]
