# Generated by Django 3.1.4 on 2021-02-22 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0007_auto_20201016_1942'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='themefield',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='themefieldoptions',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='themeform',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='themekanbancard',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='themekanbancardfield',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='themekanbandimensionorder',
            managers=[
            ],
        ),
        migrations.CreateModel(
            name='ThemeKanbanDefault',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theme.themeform')),
                ('kanban_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='theme.themekanbancard')),
                ('kanban_dimension', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='theme.themekanbandimensionorder')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theme.theme')),
            ],
            options={
                'db_table': 'theme_kanban_default',
            },
        ),
    ]
