# Generated by Django 3.1.4 on 2021-02-22 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0008_auto_20210222_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='themekanbandefault',
            name='kanban_dimension',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='theme.themefield'),
        ),
    ]
