# Generated by Django 3.1.4 on 2021-02-24 04:38

from django.db import migrations
def migrate_add_order_to_kanban_card_field(apps, schema_editor):
    ThemeKanbanCardField = apps.get_model('kanban', 'ThemeKanbanCardField')

    last_kanban_card_id = None
    order = 0
    for theme_kanban_card_field in ThemeKanbanCardField.objects.all().order_by('kanban_card_id', 'id'):
        if theme_kanban_card_field.kanban_card.id != last_kanban_card_id:
            order = 0
        else:
            order = order + 1
        theme_kanban_card_field.order = order
        theme_kanban_card_field.save()

        last_kanban_card_id = theme_kanban_card_field.kanban_card.id

class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0004_kanbancardfield_order'),
    ]

    operations = [
        migrations.RunPython(migrate_add_order_to_kanban_card_field)
    ]


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0011_themekanbancardfield_order'),
    ]

    operations = [
    ]
