# Generated by Django 3.1.4 on 2021-02-25 23:52

from django.db import migrations

import uuid


def migrate_add_uuid_to_theme_field_options(apps, schema_editor):
    ThemeFieldOptions = apps.get_model('theme', 'ThemeFieldOptions')

    for them_field_option in ThemeFieldOptions.objects.all():
        them_field_option.uuid = uuid.uuid4()
        them_field_option.save()


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0013_themefieldoptions_uuid'),
    ]

    operations = [
        migrations.RunPython(migrate_add_uuid_to_theme_field_options)
    ]
