# Generated by Django 3.1.4 on 2021-02-27 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0014_auto_20210225_2352'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='themekanbancardfield',
            options={'ordering': ('order',)},
        ),
    ]
