# Generated by Django 3.1.4 on 2021-04-13 00:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0015_auto_20210227_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='themefield',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name='themeform',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
