# Generated by Django 3.1.4 on 2021-04-13 03:29

from django.db import migrations, transaction

import uuid


@transaction.atomic
def migrate_uuids_in_theme_form_and_theme_field(apps, schema_editor):
    ThemeForm = apps.get_model('theme', 'ThemeForm')
    ThemeField = apps.get_model('theme', 'ThemeField')

    for theme_field_instance in ThemeField.objects.all():
        theme_field_instance.uuid = uuid.uuid4()
        theme_field_instance.save()

    for theme_form_instance in ThemeForm.objects.all():
        theme_form_instance.uuid = uuid.uuid4()
        theme_form_instance.save()
    


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0016_auto_20210413_0050'),
    ]

    operations = [
        migrations.RunPython(migrate_uuids_in_theme_form_and_theme_field)
    ]
