# Generated by Django 3.1.4 on 2021-06-07 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0021_auto_20210607_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='themeformulavariable',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theme_field_formula_variables', to='theme.themefield'),
        ),
        migrations.AlterField(
            model_name='themeformulavariable',
            name='variable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theme_field_formula_variable_variables', to='theme.themefield'),
        ),
    ]
