# Generated by Django 3.1.4 on 2021-06-25 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0022_auto_20210607_1747'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='themeformulavariable',
            options={'ordering': ('order',)},
        ),
    ]
