# Generated by Django 3.2.5 on 2021-08-19 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rich_text', '0020_auto_20210210_2309'),
        ('theme', '0023_auto_20210625_1419'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThemePDFTemplateConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=500)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theme.theme')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theme.themeform')),
                ('rich_text_page', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rich_text.textpage')),
            ],
            options={
                'db_table': 'theme_pdf_template_configuration',
            },
        ),
        migrations.CreateModel(
            name='ThemePDFTemplateConfigurationVariables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theme.themefield')),
                ('pdf_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theme_template_configuration_variables', to='theme.themepdftemplateconfiguration')),
            ],
            options={
                'db_table': 'theme_pdf_template_configuration_variables',
            },
        ),
    ]
