# Generated by Django 3.2.5 on 2021-08-19 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0024_themepdftemplateconfiguration_themepdftemplateconfigurationvariables'),
    ]

    operations = [
        migrations.RenameField(
            model_name='themepdftemplateconfiguration',
            old_name='company',
            new_name='theme',
        ),
    ]
