# Generated by Django 3.1.4 on 2021-01-03 00:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0010_auto_20200902_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='DraftType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('order', models.BigIntegerField(default=1)),
            ],
            options={
                'db_table': 'draft_type',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='DraftValueType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('order', models.BigIntegerField(default=1)),
            ],
            options={
                'db_table': 'draft_value_type',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='Draft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bucket', models.CharField(blank=True, default='reflow-crm', max_length=200, null=True)),
                ('file_draft_path', models.CharField(blank=True, default='file-draft', max_length=250, null=True)),
                ('file_url', models.CharField(blank=True, max_length=1000, null=True)),
                ('file_size', models.BigIntegerField(blank=True, default=0, null=True)),
                ('value', models.TextField(blank=True, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_drafts', to='authentication.company')),
                ('draft_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='draft.drafttype')),
                ('draft_value_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='draft.draftvaluetype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_drafts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'draft',
            },
        ),
    ]
