# Generated by Django 3.1.4 on 2021-01-05 05:35

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='draft',
            managers=[
                ('draft_', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='draft',
            name='draft_value_type',
        ),
        migrations.DeleteModel(
            name='DraftValueType',
        ),
    ]
