# Generated by Django 3.1.4 on 2021-03-17 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0002_auto_20210105_0535'),
    ]

    operations = [
        migrations.AddField(
            model_name='draft',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
