# Generated by Django 3.1 on 2020-10-16 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rich_text', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textcontent',
            name='block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rich_text_block_contents', to='rich_text.textblock'),
        ),
    ]
