# Generated by Django 3.1 on 2020-10-16 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rich_text', '0002_auto_20201016_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='textcontent',
            name='link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
