# Generated by Django 3.1 on 2020-10-19 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rich_text', '0003_textcontent_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textcontent',
            name='latex_equation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='textcontent',
            name='marker_color',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='textcontent',
            name='text_color',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
