# Generated by Django 3.1 on 2020-10-27 00:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('rich_text', '0004_auto_20201019_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='textblock',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name='textcontent',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4),
        ),
    ]
