# Generated by Django 3.1 on 2020-11-26 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rich_text', '0005_auto_20201027_0030'),
    ]

    operations = [
        migrations.AddField(
            model_name='textcontent',
            name='custom_value',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='textcontent',
            name='is_custom',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='textcontent',
            name='latex_equation',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='textcontent',
            name='link',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='textcontent',
            name='marker_color',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='textcontent',
            name='text_color',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
    ]
