# Generated by Django 3.1 on 2020-12-01 01:08

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('rich_text', '0006_auto_20201126_1627'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='textblocktype',
            managers=[
                ('rich_text_', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='texttableoption',
            name='border_color',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
