# Generated by Django 3.1.4 on 2021-01-06 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rich_text', '0009_textcontent_text_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textimageoption',
            name='size_relative_to_view',
        ),
        migrations.AddField(
            model_name='textimageoption',
            name='link',
            field=models.TextField(blank=True, default=''),
        ),
    ]
