# Generated by Django 3.1.4 on 2021-01-06 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rich_text', '0010_auto_20210106_0031'),
    ]

    operations = [
        migrations.AddField(
            model_name='textimageoption',
            name='bucket',
            field=models.CharField(blank=True, default='reflow-crm', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='textimageoption',
            name='file_image_path',
            field=models.CharField(blank=True, default='rich-text/file-rich-text-image', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='textimageoption',
            name='file_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='textimageoption',
            name='file_size',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='textimageoption',
            name='file_url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='textimageoption',
            name='size_relative_to_view',
            field=models.BigIntegerField(default=1),
        ),
    ]
