# Generated by Django 3.1.4 on 2021-01-13 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rich_text', '0012_auto_20210107_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textimageoption',
            name='size_relative_to_view',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=4),
        ),
    ]
