# Generated by Django 3.1.4 on 2021-01-13 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rich_text', '0014_auto_20210113_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textimageoption',
            name='size_relative_to_view',
            field=models.DecimalField(decimal_places=20, default=1.0, max_digits=25),
        ),
    ]
