# Generated by Django 3.1.4 on 2021-01-15 02:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('rich_text', '0015_auto_20210113_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='textimageoption',
            name='file_image_uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4),
        ),
    ]
