# Generated by Django 3.1.4 on 2021-01-26 21:26

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('rich_text', '0017_auto_20210126_2029'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='texttableoptioncolumndimension',
            options={'ordering': ('order',)},
        ),
        migrations.AlterModelOptions(
            name='texttableoptionrowdimension',
            options={'ordering': ('order',)},
        ),
        migrations.AlterModelManagers(
            name='texttableoption',
            managers=[
                ('rich_text_', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='texttableoptioncolumndimension',
            name='order',
            field=models.BigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='texttableoptionrowdimension',
            name='order',
            field=models.BigIntegerField(default=1),
        ),
    ]
