# Generated by Django 3.1.4 on 2021-01-27 13:15

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('rich_text', '0018_auto_20210126_2126'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='texttableoptioncolumndimension',
            managers=[
                ('rich_text_', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='texttableoptionrowdimension',
            managers=[
                ('rich_text_', django.db.models.manager.Manager()),
            ],
        ),
    ]
