# Generated by Django 3.1.4 on 2021-02-10 23:09

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('rich_text', '0019_auto_20210127_1315'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='textblocktypecancontaintype',
            managers=[
                ('rich_text_', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='texttableoptioncolumndimension',
            name='width',
            field=models.FloatField(default=None, null=True),
        ),
    ]
