# Generated by Django 3.2.5 on 2021-08-02 15:48

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'event',
            },
        ),
        migrations.CreateModel(
            name='TypeOfEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=280)),
            ],
            options={
                'db_table': 'type_of_event',
            },
            managers=[
                ('analytics_', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='EventData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter_name', models.CharField(max_length=300)),
                ('value', models.TextField()),
                ('event', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='analytics.event')),
            ],
            options={
                'db_table': 'event_data',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='type_of_event',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='analytics.typeofevent'),
        ),
    ]
