# Generated by Django 3.2.5 on 2021-08-09 03:44

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='event',
            managers=[
                ('analytics_', django.db.models.manager.Manager()),
            ],
        ),
    ]
