# Generated by Django 3.2.5 on 2021-10-20 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_apiaccesstoken'),
        ('analytics', '0002_alter_event_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyAnalytics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_employees', models.IntegerField(default=0, null=True)),
                ('sector', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('company', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='authentication.company')),
            ],
            options={
                'db_table': 'company_analytics',
            },
        ),
    ]
