# Generated by Django 3.2.5 on 2021-11-09 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_survey_surveyanswer_surveycriteriadata_surveyquestion_surveyquestionanswer_surveyquestionoption'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyanswer',
            name='survey',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='survey_answers', to='analytics.survey'),
        ),
    ]
