# Generated by Django 3.2.5 on 2021-11-10 01:12

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_surveyanswer_survey'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='surveyquestionanswer',
            managers=[
                ('analytics_', django.db.models.manager.Manager()),
            ],
        ),
    ]
