# Generated by Django 3.2.5 on 2021-11-10 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0006_alter_surveyquestionanswer_managers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='surveyquestionoption',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='surveyquestionoption',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='surveyquestionoption',
            name='range_value',
            field=models.IntegerField(null=True),
        ),
    ]
