version: '3.3'
services:
  reflow_server:
    build: .
    command: "sh scripts/production/deploy.sh"
    env_file:
        - .env
    volumes:
      - .:/code
      - "${EB_LOG_BASE_DIR}/reflow_server:/code/logs"
    ports:
      - "8000:8000"