# Generated by Django 3.2.5 on 2021-08-23 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('formulary', '0025_auto_20210625_1426'),
        ('authentication', '0011_publicaccess'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filter_company', to='authentication.company')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filter_form', to='formulary.form')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filter_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'filter',
            },
        ),
        migrations.CreateModel(
            name='FilterConditionalType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=280)),
            ],
            options={
                'db_table': 'filter_conditional_type',
            },
        ),
        migrations.CreateModel(
            name='FilterConectorType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=280)),
            ],
            options={
                'db_table': 'filter_conector_type',
            },
        ),
        migrations.CreateModel(
            name='FilterCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_negation', models.BooleanField(default=False)),
                ('value', models.CharField(blank=True, max_length=1000)),
                ('value2', models.CharField(blank=True, max_length=1000, null=True)),
                ('order', models.IntegerField()),
                ('conditional_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filter.filterconditionaltype')),
                ('conector_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='filter.filterconectortype')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filter_condition_user', to='formulary.field')),
                ('filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filter_condition_filter', to='filter.filter')),
            ],
            options={
                'db_table': 'filter_condition',
                'ordering': ('order',),
            },
        ),
    ]
