# Generated by Django 3.2.5 on 2021-09-09 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formulary', '0025_auto_20210625_1426'),
        ('authentication', '0011_publicaccess'),
        ('filter', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filterconditionaltype',
            options={'ordering': ('order',)},
        ),
        migrations.AlterModelOptions(
            name='filterconectortype',
            options={'ordering': ('order',)},
        ),
        migrations.RemoveField(
            model_name='filter',
            name='user',
        ),
        migrations.AddField(
            model_name='filterconditionaltype',
            name='order',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='filterconectortype',
            name='order',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='filter',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_filters', to='authentication.company'),
        ),
        migrations.AlterField(
            model_name='filter',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_filters', to='formulary.form'),
        ),
        migrations.CreateModel(
            name='FilterConditionalTypeByFieldTypeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formulary.fieldtype')),
                ('filter_conditional_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filter.filterconditionaltype')),
            ],
            options={
                'db_table': 'filter_conditional_type_by_field_type_type',
            },
        ),
    ]
