# Generated by Django 3.0.6 on 2020-07-19 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chargefrequencytype',
            options={'ordering': ('order',)},
        ),
        migrations.AlterModelOptions(
            name='chargetype',
            options={'ordering': ('order',)},
        ),
        migrations.AlterModelOptions(
            name='individualchargevaluetype',
            options={'ordering': ('order',)},
        ),
        migrations.AlterModelOptions(
            name='invoicedatetype',
            options={'ordering': ('order',)},
        ),
        migrations.AlterModelOptions(
            name='paymentmethodtype',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='chargefrequencytype',
            name='order',
            field=models.BigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='chargetype',
            name='order',
            field=models.BigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='individualchargevaluetype',
            name='order',
            field=models.BigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='invoicedatetype',
            name='order',
            field=models.BigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='paymentmethodtype',
            name='order',
            field=models.BigIntegerField(default=1),
        ),
    ]
