# Generated by Django 3.0.6 on 2020-07-31 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_auto_20200719_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualchargevaluetype',
            name='charge_group_name',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
    ]
