# Generated by Django 3.0.6 on 2020-08-04 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_company_additional_details'),
        ('billing', '0004_discountbyindividualvalue_static'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discountbyindividualvaluequantity',
            name='static',
        ),
        migrations.AlterModelTable(
            name='discountbyindividualvaluequantity',
            table='discount_by_individual_value_quantity',
        ),
        migrations.CreateModel(
            name='DiscountByIndividualNameForCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('name', models.CharField(max_length=250)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.Company')),
                ('individual_charge_value_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.IndividualChargeValueType')),
            ],
            options={
                'db_table': 'discount_by_individual_name_for_company',
            },
        ),
    ]
