# Generated by Django 3.1 on 2020-08-28 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_auto_20200828_1928'),
        ('billing', '0006_auto_20200804_0557'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyBilling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(default=None, max_length=500, null=True)),
                ('zip_code', models.CharField(default=None, max_length=500, null=True)),
                ('street', models.CharField(default=None, max_length=500, null=True)),
                ('number', models.IntegerField(null=True)),
                ('neighborhood', models.CharField(default=None, max_length=500, null=True)),
                ('country', models.CharField(default=None, max_length=280, null=True)),
                ('state', models.CharField(default=None, max_length=280, null=True)),
                ('city', models.CharField(default=None, max_length=280, null=True)),
                ('cnpj', models.CharField(default=None, max_length=280, null=True)),
                ('additional_details', models.CharField(default=None, max_length=280, null=True)),
                ('is_supercompany', models.BooleanField(default=False)),
                ('is_paying_company', models.BooleanField(default=False)),
                ('vindi_plan_id', models.CharField(db_index=True, default=None, max_length=280, null=True)),
                ('vindi_client_id', models.CharField(db_index=True, default=None, max_length=280, null=True)),
                ('vindi_product_id', models.CharField(db_index=True, default=None, max_length=280, null=True)),
                ('vindi_payment_profile_id', models.CharField(db_index=True, default=None, max_length=280, null=True)),
                ('vindi_signature_id', models.CharField(db_index=True, default=None, max_length=280, null=True)),
                ('charge_frequency_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='billing.chargefrequencytype')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.company')),
                ('invoice_date_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='billing.invoicedatetype')),
                ('payment_method_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='billing.paymentmethodtype')),
            ],
            options={
                'db_table': 'company_billing',
            },
        ),
    ]
