# Generated by Django 3.1 on 2020-08-28 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_auto_20200828_2011'),
        ('billing', '0009_auto_20200828_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companybilling',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing_company', to='authentication.company'),
        ),
    ]
