# Generated by Django 3.1.4 on 2021-01-21 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_auto_20200828_2112'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerDefaultAndDiscounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_name', models.CharField(max_length=200)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('default_quantity', models.IntegerField(blank=True, null=True)),
                ('individual_charge_value_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.individualchargevaluetype')),
            ],
            options={
                'db_table': 'partner_default_and_discounts',
            },
        ),
    ]
