# Generated by Django 3.1.4 on 2021-01-26 20:29

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0011_partnerdefaultanddiscounts'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='companycoupons',
            managers=[
                ('billing_', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='discountcoupon',
            managers=[
                ('billing_', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='partnerdefaultanddiscounts',
            managers=[
                ('billing_', django.db.models.manager.Manager()),
            ],
        ),
    ]
