# Generated by Django 3.2.5 on 2021-12-07 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0015_companychargesent'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
            ],
            options={
                'db_table': 'billing_plan',
            },
        ),
        migrations.CreateModel(
            name='BillingPlanPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_quantity', models.IntegerField()),
                ('billing_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.billingplan')),
                ('individual_charge_value_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.individualchargevaluetype')),
            ],
            options={
                'db_table': 'billing_plan_permission',
            },
        ),
    ]
