# Generated by Django 3.2.5 on 2021-12-10 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0017_auto_20211210_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingplanpermission',
            name='default_quantity',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
