# Generated by Django 3.2.5 on 2021-12-16 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0020_billingplanpermission_has_soft_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountbyindividualvaluequantity',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='billing.billingplan'),
        ),
    ]
