# Generated by Django 3.2.5 on 2021-12-17 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0021_discountbyindividualvaluequantity_plan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billingplan',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='billingplan',
            name='order',
            field=models.BigIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='billingplanpermission',
            name='billing_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_plan_permissions', to='billing.billingplan'),
        ),
    ]
