# Generated by Django 3.2.5 on 2022-01-10 19:56

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0022_auto_20211217_1640'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='billingplan',
            managers=[
                ('billing_', django.db.models.manager.Manager()),
            ],
        ),
    ]
