# Generated by Django 3.1.4 on 2021-02-20 05:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0010_auto_20200902_1555'),
        ('formulary', '0002_auto_20200719_1720'),
        ('kanban', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kanbancard',
            name='company',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.company'),
        ),
        migrations.AddField(
            model_name='kanbancard',
            name='form',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='formulary.form'),
        ),
        migrations.CreateModel(
            name='KanbanDefault',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.company')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formulary.form')),
                ('kanban_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kanban.kanbancard')),
                ('kanban_dimension', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='formulary.field')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'kanban_default',
            },
        ),
        migrations.CreateModel(
            name='KanbanCollapsedOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.company')),
                ('options', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formulary.fieldoptions')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'kanban_collapsed_option',
            },
        ),
    ]
