# Generated by Django 3.1.4 on 2021-02-24 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0003_auto_20210220_0556'),
    ]

    operations = [
        migrations.AddField(
            model_name='kanbancardfield',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
