# Generated by Django 3.1.4 on 2021-02-25 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0005_auto_20210224_0438'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kanbancollapsedoption',
            old_name='options',
            new_name='field_option',
        ),
    ]
