# Generated by Django 3.1.4 on 2021-02-27 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0006_auto_20210225_1717'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kanbancardfield',
            options={'ordering': ('order',)},
        ),
    ]
