# Generated by Django 3.0.6 on 2020-06-08 19:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('formulary', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_dynamic_form', to='authentication.Company')),
                ('depends_on', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='depends_on_dynamic_form', to='data.DynamicForm')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formulary.Form')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dynamic_forms',
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='FormValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_configuration_mask', models.CharField(blank=True, max_length=250, null=True)),
                ('formula_configuration', models.CharField(blank=True, max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.TextField(blank=True, db_index=True, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_value', to='authentication.Company')),
                ('date_configuration_date_format_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='formulary.FieldDateFormatType')),
                ('field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='field_value', to='formulary.Field')),
                ('field_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='field_type_value', to='formulary.FieldType')),
                ('form', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_form_value', to='data.DynamicForm')),
                ('form_field_as_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='formulary.Field')),
                ('number_configuration_number_format_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='formulary.FieldNumberFormatType')),
                ('period_configuration_period_interval_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='formulary.FieldPeriodIntervalType')),
            ],
            options={
                'db_table': 'form_value',
            },
        ),
        migrations.CreateModel(
            name='Attachments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.CharField(blank=True, max_length=500, null=True)),
                ('bucket', models.CharField(default='', max_length=200)),
                ('file_attachments_path', models.CharField(default='', max_length=250)),
                ('file_url', models.CharField(blank=True, max_length=1000, null=True)),
                ('file_size', models.BigIntegerField(default=0)),
                ('date', models.DateField(auto_now=True)),
                ('field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='field_attachment', to='formulary.Field')),
                ('form', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_form_attachment', to='data.DynamicForm')),
            ],
            options={
                'db_table': 'attachments',
            },
        ),
    ]
