# Generated by Django 3.0.6 on 2020-06-14 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachments',
            name='bucket',
            field=models.CharField(default='reflow-crm', max_length=200),
        ),
        migrations.AlterField(
            model_name='attachments',
            name='file_attachments_path',
            field=models.CharField(default='file-attachments', max_length=250),
        ),
    ]
