# Generated by Django 3.1.4 on 2021-05-03 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_dynamicform_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='formvalue',
            name='is_long_text_rich_text',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
