# Generated by Django 3.1.4 on 2021-05-14 15:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_formvalue_is_long_text_rich_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicform',
            name='uuid',
            field=models.UUIDField(blank=True, db_index=True, default=uuid.uuid4, null=True),
        ),
    ]
