# Generated by Django 3.1.4 on 2021-05-20 23:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('formulary', '0018_auto_20210507_1829'),
        ('authentication', '0011_publicaccess'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data', '0007_auto_20210514_1559'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractFileData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_id', models.UUIDField(default=uuid.uuid4)),
                ('file', models.TextField()),
                ('file_format', models.CharField(default='csv', max_length=10)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.company')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formulary.form')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'extract_file_data',
            },
        ),
    ]
