# Generated by Django 3.2.5 on 2021-11-22 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_auto_20211018_2247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formvalue',
            name='number_configuration_mask',
        ),
    ]
