# Generated by Django 3.0.6 on 2020-05-29 15:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConditionalType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(db_index=True, max_length=150)),
                ('label_name', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'conditional_type',
            },
        ),
        migrations.CreateModel(
            name='DynamicForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_dynamic_form', to='authentication.Company')),
                ('depends_on', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='depends_on_dynamic_form', to='formulary.DynamicForm')),
            ],
            options={
                'db_table': 'dynamic_forms',
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_configuration_mask', models.CharField(blank=True, max_length=250, null=True)),
                ('formula_configuration', models.CharField(blank=True, max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=300)),
                ('label_name', models.CharField(blank=True, max_length=300, null=True)),
                ('placeholder', models.CharField(blank=True, max_length=450, null=True)),
                ('required', models.BooleanField(default=True)),
                ('order', models.BigIntegerField()),
                ('is_unique', models.BooleanField(default=False)),
                ('field_is_hidden', models.BooleanField(default=False)),
                ('label_is_hidden', models.BooleanField(default=False)),
                ('date_configuration_auto_create', models.BooleanField(default=False)),
                ('date_configuration_auto_update', models.BooleanField(default=False)),
                ('number_configuration_allow_negative', models.BooleanField(default=True)),
                ('number_configuration_allow_zero', models.BooleanField(default=True)),
                ('enabled', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'db_table': 'field',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='FieldDateFormatType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(db_index=True, max_length=200)),
                ('label_name', models.CharField(max_length=250)),
                ('format', models.CharField(max_length=250)),
                ('order', models.BigIntegerField()),
            ],
            options={
                'db_table': 'field_date_format_type',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='FieldNumberFormatType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(db_index=True, max_length=200)),
                ('label_name', models.CharField(max_length=250)),
                ('precision', models.BigIntegerField(default=1)),
                ('prefix', models.CharField(max_length=250, null=True)),
                ('suffix', models.CharField(max_length=250, null=True)),
                ('thousand_separator', models.CharField(max_length=10, null=True)),
                ('decimal_separator', models.CharField(max_length=10, null=True)),
                ('order', models.BigIntegerField()),
                ('base', models.BigIntegerField(default=1)),
            ],
            options={
                'db_table': 'field_number_format_type',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='FieldOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('option', models.CharField(db_index=True, max_length=500)),
                ('order', models.BigIntegerField()),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_option', to='formulary.Field')),
            ],
            options={
                'db_table': 'field_options',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='FieldPeriodIntervalType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(db_index=True, max_length=200)),
                ('label_name', models.CharField(max_length=250)),
                ('in_seconds', models.BigIntegerField()),
            ],
            options={
                'db_table': 'field_period_interval_type',
            },
        ),
        migrations.CreateModel(
            name='FieldType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(db_index=True, max_length=200)),
                ('label_name', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'field_type',
            },
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('form_name', models.CharField(db_index=True, max_length=150)),
                ('label_name', models.CharField(max_length=150)),
                ('order', models.BigIntegerField()),
                ('conditional_value', models.CharField(blank=True, max_length=200, null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.Company')),
                ('conditional_on_field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conditional_on_field', to='formulary.Field')),
                ('conditional_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='formulary.ConditionalType')),
                ('depends_on', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='depends_on_form', to='formulary.Form')),
            ],
            options={
                'db_table': 'form',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='SectionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(db_index=True, max_length=150)),
                ('label_name', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'form_type',
            },
        ),
        migrations.CreateModel(
            name='OptionAccessedBy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_accessed_by', to='formulary.FieldOptions')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_accessed_by_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'option_accessed_by',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('enabled', models.BooleanField(default=False)),
                ('order', models.BigIntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.Company')),
            ],
            options={
                'db_table': 'group',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='FormValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_configuration_mask', models.CharField(blank=True, max_length=250, null=True)),
                ('formula_configuration', models.CharField(blank=True, max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.TextField(blank=True, db_index=True, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_value', to='authentication.Company')),
                ('date_configuration_date_format_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='formulary.FieldDateFormatType')),
                ('field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='field_value', to='formulary.Field')),
                ('field_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='field_type_value', to='formulary.FieldType')),
                ('form', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_form_value', to='formulary.DynamicForm')),
                ('form_field_as_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='formulary.Field')),
                ('number_configuration_number_format_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='formulary.FieldNumberFormatType')),
                ('period_configuration_period_interval_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='formulary.FieldPeriodIntervalType')),
            ],
            options={
                'db_table': 'form_value',
            },
        ),
        migrations.CreateModel(
            name='FormAccessedBy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formulary.Form')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_accessed_by_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'form_accessed_by',
            },
        ),
        migrations.AddField(
            model_name='form',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='form_group', to='formulary.Group'),
        ),
        migrations.AddField(
            model_name='form',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formulary.SectionType'),
        ),
        migrations.AddField(
            model_name='field',
            name='date_configuration_date_format_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='formulary.FieldDateFormatType'),
        ),
        migrations.AddField(
            model_name='field',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_fields', to='formulary.Form'),
        ),
        migrations.AddField(
            model_name='field',
            name='form_field_as_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='formulary.Field'),
        ),
        migrations.AddField(
            model_name='field',
            name='number_configuration_number_format_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='formulary.FieldNumberFormatType'),
        ),
        migrations.AddField(
            model_name='field',
            name='period_configuration_period_interval_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='formulary.FieldPeriodIntervalType'),
        ),
        migrations.AddField(
            model_name='field',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formulary.FieldType'),
        ),
        migrations.AddField(
            model_name='dynamicform',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formulary.Form'),
        ),
        migrations.AddField(
            model_name='dynamicform',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Attachments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.CharField(blank=True, max_length=500, null=True)),
                ('bucket', models.CharField(default='', max_length=200)),
                ('file_attachments_path', models.CharField(default='', max_length=250)),
                ('file_url', models.CharField(blank=True, max_length=1000, null=True)),
                ('file_size', models.BigIntegerField(default=0)),
                ('date', models.DateField(auto_now=True)),
                ('field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='field_attachment', to='formulary.Field')),
                ('form', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_form_attachment', to='formulary.DynamicForm')),
            ],
            options={
                'db_table': 'attachments',
            },
        ),
    ]
