# Generated by Django 3.0.6 on 2020-07-19 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulary', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conditionaltype',
            options={'ordering': ('order',)},
        ),
        migrations.AlterModelOptions(
            name='fieldperiodintervaltype',
            options={'ordering': ('order',)},
        ),
        migrations.AlterModelOptions(
            name='fieldtype',
            options={'ordering': ('order',)},
        ),
        migrations.AlterModelOptions(
            name='sectiontype',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='conditionaltype',
            name='order',
            field=models.BigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='fieldperiodintervaltype',
            name='order',
            field=models.BigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='fieldtype',
            name='order',
            field=models.BigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='sectiontype',
            name='order',
            field=models.BigIntegerField(default=1),
        ),
    ]
