# Generated by Django 3.1.4 on 2021-02-25 22:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('formulary', '0002_auto_20200719_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldoptions',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
