# Generated by Django 3.1.4 on 2021-02-27 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_publicaccess'),
        ('formulary', '0004_auto_20210225_2352'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicAccessForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formulary.form')),
                ('public_access', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.publicaccess')),
            ],
            options={
                'db_table': 'public_form',
            },
        ),
        migrations.CreateModel(
            name='PublicAccessField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formulary.field')),
                ('public_access', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.publicaccess')),
                ('public_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formulary.publicaccessform')),
            ],
            options={
                'db_table': 'public_field',
            },
        ),
    ]
