# Generated by Django 3.1.4 on 2021-03-02 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formulary', '0005_publicaccessfield_publicaccessform'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publicaccessfield',
            old_name='form',
            new_name='field',
        ),
        migrations.AlterModelTable(
            name='publicaccessfield',
            table='public_access_field',
        ),
        migrations.AlterModelTable(
            name='publicaccessform',
            table='public_access_form',
        ),
    ]
