# Generated by Django 3.1.4 on 2021-03-07 21:57

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('formulary', '0006_auto_20210302_1652'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='publicaccessform',
            managers=[
                ('formulary_', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='publicaccessfield',
            name='public_form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_access_form_public_access_fields', to='formulary.publicaccessform'),
        ),
    ]
