# Generated by Django 3.1.4 on 2021-03-17 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulary', '0007_auto_20210307_2157'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='publicaccessform',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='publicaccessform',
            name='description_message',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='publicaccessform',
            name='greetings_message',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='publicaccessform',
            name='is_to_submit_another_response_button',
            field=models.BooleanField(default=False),
        ),
    ]
