# Generated by Django 3.1.4 on 2021-03-25 17:16

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('formulary', '0010_auto_20210325_0155'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='defaultfieldvalueattachments',
            managers=[
                ('formulary_', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='defaultfieldvalueattachments',
            name='value',
        ),
    ]
