# Generated by Django 3.1.4 on 2021-03-26 01:12

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('formulary', '0011_auto_20210325_1716'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='defaultfieldvalue',
            managers=[
                ('formulary_', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RenameField(
            model_name='defaultfieldvalueattachments',
            old_name='file_attachments_path',
            new_name='file_default_attachments_path',
        ),
    ]
