# Generated by Django 3.1.4 on 2021-04-13 00:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('formulary', '0012_auto_20210326_0112'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name='form',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
