# Generated by Django 3.1.4 on 2021-04-13 03:30

from django.db import migrations, transaction

import uuid


@transaction.atomic
def migrate_uuids_in_form_and_field(apps, schema_editor):
    Form = apps.get_model('formulary', 'Form')
    Field = apps.get_model('formulary', 'Field')

    for field_instance in Field.objects.all():
        field_instance.uuid = uuid.uuid4()
        field_instance.save()

    for form_instance in Form.objects.all():
        form_instance.uuid = uuid.uuid4()
        form_instance.save()
    

class Migration(migrations.Migration):

    dependencies = [
        ('formulary', '0013_auto_20210413_0050'),
    ]

    operations = [
        migrations.RunPython(migrate_uuids_in_form_and_field)
    ]
