# Generated by Django 3.1.4 on 2021-04-17 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulary', '0014_auto_20210413_0330'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='conditional_excludes_data_if_not_set',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='form',
            name='show_label_name',
            field=models.BooleanField(default=True),
        ),
    ]
