# Generated by Django 3.1.4 on 2021-05-03 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulary', '0015_auto_20210417_0106'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='is_long_text_rich_text',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
