# Generated by Django 3.1.4 on 2021-05-04 23:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('formulary', '0016_field_is_long_text_rich_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccessedBy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formulary.field')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_accessed_by_user', to=settings.AUTH_USER_MODEL)),
                ('user_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_accessed_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_accessed_by',
            },
        ),
    ]
