# Generated by Django 3.1.4 on 2021-05-07 18:29

from django.db import migrations, transaction


@transaction.atomic
def migrate_user_accessed_by(apps, schema_editor):
    Company = apps.get_model('authentication', 'Company')
    UserExtended = apps.get_model('authentication', 'UserExtended')
    UserAccessedBy = apps.get_model('formulary', 'UserAccessedBy')
    Field = apps.get_model('formulary', 'Field')

    all_companies = Company.objects.all()
    for company in all_companies:
        users_fields = Field.objects.filter(form__depends_on__group__company_id=company.id, type__type='user')
        users_in_company = UserExtended.objects.filter(company=company)
        for users_field in users_fields:
            for user in users_in_company:
                for user_option in users_in_company:
                    UserAccessedBy.objects.update_or_create(
                        field=users_field,
                        user=user,
                        user_option=user_option
                    )

class Migration(migrations.Migration):

    dependencies = [
        ('formulary', '0017_useraccessedby'),
    ]

    operations = [
        migrations.RunPython(migrate_user_accessed_by)
    ]
