# Generated by Django 3.1.4 on 2021-05-27 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulary', '0018_auto_20210507_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldtype',
            name='is_dynamic_evaluated',
            field=models.BooleanField(default=False),
        ),
    ]
