# Generated by Django 3.1.4 on 2021-06-07 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formulary', '0022_auto_20210607_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulavariable',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_formula_variables', to='formulary.field'),
        ),
        migrations.AlterField(
            model_name='formulavariable',
            name='variable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_formula_variable_variables', to='formulary.field'),
        ),
    ]
