# Generated by Django 3.1.4 on 2021-06-25 14:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('formulary', '0023_auto_20210607_1747'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formulavariable',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='formulavariable',
            name='uuid',
            field=models.UUIDField(blank=True, db_index=True, default=uuid.uuid4, null=True),
        ),
    ]
