# Generated by Django 3.1.4 on 2021-06-25 14:26
from django.db import migrations, transaction

import uuid


@transaction.atomic
def migrate_uuids_in_formula_variable(apps, schema_editor):
    FormulaVariable = apps.get_model('formulary', 'FormulaVariable')

    for formula_variable in FormulaVariable.objects.all():
        formula_variable.uuid = uuid.uuid4()
        formula_variable.save()


class Migration(migrations.Migration):

    dependencies = [
        ('formulary', '0024_auto_20210625_1419'),
    ]

    operations = [
        migrations.RunPython(migrate_uuids_in_formula_variable)
    ]
