# Generated by Django 3.2.5 on 2021-10-11 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulary', '0025_auto_20210625_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='formula_configuration',
            field=models.TextField(blank=True, null=True),
        ),
    ]
